# Generated by Django 4.2.23 on 2025-08-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("target_share", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("abbreviation", models.CharField(max_length=10)),
                (
                    "employee_type",
                    models.CharField(
                        choices=[("FULL", "Full"), ("APPRENTICE", "Apprentice")],
                        max_length=20,
                    ),
                ),
                ("apprenticeship_year", models.IntegerField(blank=True, null=True)),
                (
                    "workload_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "personal_shift_quota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="core.team",
                    ),
                ),
            ],
        ),
    ]
