# Generated by Django 4.2.23 on 2025-08-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("monday_required", models.PositiveIntegerField(default=0)),
                ("tuesday_required", models.PositiveIntegerField(default=0)),
                ("wednesday_required", models.PositiveIntegerField(default=0)),
                ("thursday_required", models.PositiveIntegerField(default=0)),
                ("friday_required", models.PositiveIntegerField(default=0)),
                ("saturday_required", models.PositiveIntegerField(default=0)),
                ("sunday_required", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
